export const FREEMIUM_LIMITS = {
  MAX_PLAYERS_FREE: 5,
  MAX_PLAYERS_PREMIUM: 20,
  MAX_QUINIELAS_FREE: 3,
  MAX_QUINIELAS_PREMIUM: Infinity,
  INVITE_UNLOCK_THRESHOLD: 5,
  INVITE_BONUS: 5,
} as const;

export const PREDICTION_RULES = {
  EXACT_MATCH_POINTS: 3,
  CORRECT_TREND_POINTS: 1,
  NO_MATCH_POINTS: 0,
  DEADLINE_MINUTES: 5,
  MIN_MATCHES_PER_QUINIELA: 5,
  MAX_MATCHES_PER_QUINIELA: 15,
} as const;

export const QUINIELA_DEFAULTS = {
  MAX_PLAYERS: 10,
  MIN_MATCHES: 5,
  IS_PRIVATE: true,
} as const;
